server:  port: 8088
spring:
  profiles:
    active: native
  cloud:
    config:
      server:        native:          search-locations:          - file:\\\D:\projetos\desafio-unbox\backend\unbox-general-configs